### ISSUE TITLE
IllegalArgumentException: Surface had no valid native window

### ISSUE THREAD

**Issue by wisnuwiry** [yanshouwang/camerax#8]
## Description

If the application finds an error, then the application immediately forces close

## How to reproduce error

1. Run-on Android 5 on Emulator.
2. Stop controller
3. Wait until force close

## Logs:

```
E/AndroidRuntime( 3642): java.lang.IllegalArgumentException: Surface had no valid native window.
E/AndroidRuntime( 3642): 	at android.hardware.camera2.legacy.LegacyCameraDevice.nativeSetSurfaceFormat(Native Method)
E/AndroidRuntime( 3642): 	at android.hardware.camera2.legacy.LegacyCameraDevice.setSurfaceFormat(LegacyCameraDevice.java:591)
E/AndroidRuntime( 3642): 	at android.hardware.camera2.legacy.RequestThreadManager.resetJpegSurfaceFormats(RequestThreadManager.java:505)
E/AndroidRuntime( 3642): 	at android.hardware.camera2.legacy.RequestThreadManager.access$2300(RequestThreadManager.java:63)
E/AndroidRuntime( 3642): 	at android.hardware.camera2.legacy.RequestThreadManager$5.handleMessage(RequestThreadManager.java:915)
E/AndroidRuntime( 3642): 	at android.os.Handler.dispatchMessage(Handler.java:98)
E/AndroidRuntime( 3642): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 3642): 	at android.os.HandlerThread.run(HandlerThread.java:61)

```

**Comment by yanshouwang** [comment]
The CameraX library doesn't work well on emulators with Android 10 or lower, look at [this link](https://developer.android.com/codelabs/camerax-getting-started#5), you can try your codes on a physical device:)
